name: Bug Report
description: Report a problem
title: '[BUG]: '
labels: ["triage", "bug"]
body:
  - type: markdown
    attributes:
      value: |
        Please do your best to make the issue as easy to act on as possible. Only submit here
        if there is clearly a problem with this library.
  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the software are you running?
      placeholder: 1.0.2
    validations:
      required: true
  - type: input
    attributes:
      label: Additional System Info
      description: Any other relevant system information.
      placeholder: OS version, Python version, hardware details, etc.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: input
    attributes:
      label: Is this a regression? Put the last known working version here if it is.
      description: Put the last known working version here if this is a regression.
      value: Not a regression
