[package]
name = "inchworm-units"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["toml"]
toml = ["dep:serde", "dep:toml", "inchworm-dimensions/toml"]

[dependencies]
inchworm-dimensions = { workspace = true }
serde = { workspace = true, optional = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }
